# Generated by Django 3.2.4 on 2021-07-05 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de Categoria')),
                ('nombreCategoria', models.CharField(max_length=50, verbose_name='Nombre de la categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Obras',
            fields=[
                ('idObra', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de Obras')),
                ('nombreObra', models.CharField(max_length=50, verbose_name='Nombre de la obra')),
                ('autorObra', models.CharField(max_length=50, verbose_name='Nombre Autor')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria')),
            ],
        ),
    ]
