# Generated by Django 3.2.4 on 2021-07-06 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='obras',
            name='descripcion',
            field=models.CharField(max_length=500, null=True, verbose_name='Descripcion Obras'),
        ),
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('idArtista', models.IntegerField(primary_key=True, serialize=False, verbose_name='id Artista')),
                ('nombreArtista', models.CharField(max_length=50, verbose_name='Nombre Artista')),
                ('fecha_nacimiento', models.DateTimeField(verbose_name='fecha nacimiento')),
                ('descripcionArtista', models.CharField(max_length=500, verbose_name='Descripcion artista')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.obras')),
            ],
        ),
    ]
