# Generated by Django 3.2.4 on 2021-07-06 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_obras_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='artista',
            name='imagenArtista',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='categoria',
            name='imagenCategoria',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
