# Generated by Django 3.2.4 on 2021-07-07 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210706_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obras',
            name='imagen',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=''),
        ),
    ]
