# Generated by Django 3.2.4 on 2021-07-07 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_obras_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='descripcionCategoria',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Descripcion del arte'),
        ),
    ]
